### ISSUE TITLE
Question - Babel ESM Plugin

### ISSUE THREAD

**Issue by nimaa77** [hadeeb/razzle-after-starter#1]
### Question 

How much `babel-esm-plugin` reduced from the final bundle?

**Comment by hadeeb** [comment]
Not much.

For me, `195 KB` changed to `189 KB`.
This is from a fairly new codebase which mostly uses function components.

As majority of the bundle consist of `node_modules` which are already transpiled, there won't be much difference in bundle size.

I guess there will be improvements in parse time.

I will update after I run some tests.

**Comment by nimaa77** [comment]
thanks man
